[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[build]
target = "x86_64-unknown-linux-gnu"

[env]
CC_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-gcc"
CXX_x86_64_unknown_linux_gnu = "x86_64-linux-gnu-g++"
